/* make_play_guide.js - writes handoff/play_guide.md: everything a test player needs to play ASHVALE without learning it
   from scratch (2026-10-05: "Give the account whatever information and tools it needs to know how to play the
   game"). Built from the game's own rules (src/core.js + data/), so it is always the current game:
     node tools/make_play_guide.js        (re-run after every release that changes quests, NPCs, spawns or shops) */
'use strict';
const fs = require('fs'), path = require('path');
const ROOT = path.join(__dirname, '..'), C = require(path.join(ROOT, 'src', 'core.js'));
const m = n => JSON.parse(fs.readFileSync(path.join(ROOT, 'data', n + '.json'))).data;
const zones = fs.readdirSync(path.join(ROOT, 'data')).filter(f => /^zone\..*\.json$/.test(f)).map(f => f.slice(5, -5));
const D = { items: m('items').items, monsters: m('monsters').monsters, shops: m('shops'), quests: m('quests'), rules: m('rules'), zones: zones.map(z => Object.assign({ id: z }, m('zone.' + z))), globecfg: m('globecfg') };
const c = C.create(D, { seed: 'guide' }), M = c.M, IT = D.items, MON = D.monsters, Q = D.quests.quests;
const name = k => (IT[k] && IT[k].name) || (MON[k] && MON[k].name) || k;
const npcBy = id => M.npcs.find(n => n.id === id);
const zoneAt = (x, y) => (M.zoneAt && M.zoneAt(x, y)) || '?';
const out = [];
const P = s => out.push(s);
P('# ASHVALE play guide (generated by tools/make_play_guide.js - do not edit by hand)\n');
P('How to drive the game: tools/live_play.py runs your JS inside the LIVE game (as @cinderwalker) with tools/play_lib.js loaded,');
P('so you can write `await walkTo(14, 52); await talk("maren"); await killN("wolf", 10)`. See the library section at the end.\n');
P('Coordinates are game tiles (x, y). A tick is 0.6 s. You start at the well in Ashvale village (22, 52).\n');
// quests
P('## Quests\n');
for (const qid in Q) {
  const q = Q[qid], g = npcBy(q.giver);
  P('### ' + q.name + ' (`' + qid + '`)');
  P('Giver: **' + (g ? g.name : q.giver) + '** (`' + q.giver + '`)' + (g ? ' at (' + g.x + ', ' + g.y + ') in ' + zoneAt(g.x, g.y) : ' - NOT PLACED IN ANY ZONE (bug?)') + '. Talk to the giver to start and to hand in each step.');
  (q.steps || []).forEach((s, i) => {
    const G = s.goal || {}, kind = Object.keys(G).find(k => k !== 'n');
    let what = kind === 'kill' ? 'kill ' + G.n + ' x ' + name(G.kill) : kind === 'bring' ? 'bring ' + G.n + ' x ' + name(G.bring) : kind === 'talk' ? 'talk to ' + ((npcBy(G.talk) || {}).name || G.talk) + (npcBy(G.talk) ? ' at (' + npcBy(G.talk).x + ', ' + npcBy(G.talk).y + ')' : ' (NOT PLACED - bug?)') : JSON.stringify(G);
    if (kind === 'kill') { const sp = c.S.mobs.filter(x => x.key === G.kill); what += sp.length ? ' - spawns: ' + sp.slice(0, 6).map(x => '(' + x.x + ',' + x.y + ')').join(' ') + (sp.length > 6 ? ' +' + (sp.length - 6) : '') : ' - NO SPAWN in the zones (wild herds on the globe, or not built yet)'; if (!MON[G.kill]) what += ' - UNKNOWN MONSTER KEY (bug?)'; }
    if (kind === 'bring' && !IT[G.bring]) what += ' - UNKNOWN ITEM (bug?)';
    P('- step ' + (i + 1) + ' [' + (s.zone || '?') + ']: ' + what + '; reward ' + (s.reward || 'none'));
  });
  P('');
}
// NPCs
P('## NPCs\n');
for (const n of M.npcs) P('- `' + n.id + '` ' + n.name + ' (' + n.x + ', ' + n.y + ') ' + zoneAt(n.x, n.y) + [n.shop && 'shop ' + n.shop, n.quest && 'quest ' + n.quest, n.chest && 'CHEST', n.portal && 'PORTAL ' + n.portal, n.gift && 'gift ' + n.gift + (n.giftAfter ? ' after ' + n.giftAfter.quest + ' step ' + n.giftAfter.step : ''), n.tailor && 'tailor'].filter(Boolean).map(t => ' - ' + t).join(''));
// shops
P('\n## Shops (buy prices)\n');
for (const sid in D.shops.shops || D.shops) { const sh = c.shop ? c.shop(sid) : null; if (!sh || !sh.stock) continue; P('- `' + sid + '` ' + sh.name + ': ' + sh.stock.map(k => name(k) + ' ' + (c.priceBuy ? c.priceBuy(sid, k, c.addPlayer('g_' + sid, {})) : '?')).join(', ')); }
// monsters
P('\n## Monsters in the zones (level, where)\n');
const byKey = {}; for (const x of c.S.mobs) (byKey[x.key] = byKey[x.key] || []).push(x);
for (const k in byKey) P('- `' + k + '` ' + name(k) + ' lv ' + MON[k].level + ', hp ' + MON[k].hp + ', max hit ' + MON[k].max + (MON[k].aggro ? ', aggressive' : '') + ': ' + byKey[k].slice(0, 5).map(x => '(' + x.x + ',' + x.y + ')').join(' ') + (byKey[k].length > 5 ? ' +' + (byKey[k].length - 5) : ''));
P('Wild animals (boar, deer, goat, hare, timber wolf, lizard) also live in herds out on the globe between the towns.');
// nodes
P('\n## Gathering spots (first few of each kind)\n');
const nodes = {}; const W = M.W || 600, H = M.H || 200;
for (const z of D.zones) { const o = z.origin || [0, 0], sz = z.size || [0, 0];
  for (let y = o[1]; y < o[1] + sz[1]; y++) for (let x = o[0]; x < o[0] + sz[0]; x++) { const n = c.nodeAt(c.idx(x, y)); if (!n) continue; const d = c.nodeDef(n), k = d.skill + ' ' + n.kind; (nodes[k] = nodes[k] || []).push([x, y, z.id]); } }
for (const k in nodes) P('- ' + k + ' (' + nodes[k].length + '): ' + nodes[k].slice(0, 5).map(p => '(' + p[0] + ',' + p[1] + ' ' + p[2] + ')').join(' '));
P('\nTools: woodcutting needs a hatchet, mining a pickaxe, fishing a net or a rod (the spot says which), lighting a fire a tinderbox and logs, cooking a fire (light logs: `use` the logs) - the General Store sells them. A hawk (Hawk ring worn) fishes with no tool.');
// portals and rules worth knowing
P('\n## Travel, chest, death\n');
P('- Town portals: ' + ((D.rules.portals || []).map(p => p.name + ' (' + p.x + ', ' + p.y + ')').join(', ')) + '. Touch one to attune; travel from any portal to an attuned town.');
P('- Ashvale stone: Elder Maren gives it after the Goblin Chief (quest step 3); `use` it to go home (30 min cooldown).');
P('- Chest: by the well in Ashvale (and by Saltmere\'s portal if built). Your bag and chest are one arcade wallet; new things settle by themselves.');
P('- Death: bag and worn gear drop where you die (gear, tools and Gold stay until taken; the rest rots). You wake at the well.');
P('\n## The play library (tools/play_lib.js, loaded into every live_play run)\n');
P('```\n' + fs.readFileSync(path.join(ROOT, 'tools', 'play_lib.js'), 'utf8').split('\n').filter(l => /^\s*\/\/\/ /.test(l)).map(l => l.replace(/^\s*\/\/\/ /, '')).join('\n') + '\n```');
fs.writeFileSync(path.join(ROOT, 'handoff', 'play_guide.md'), out.join('\n') + '\n');
console.log('wrote handoff/play_guide.md', out.length, 'lines');
